name: Build Documentation

on:
  repository_dispatch:
    types: [update-documentation]

permissions:
  contents: write

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Git Submodule Update
        run: git submodule update --init --remote --recursive --force

      - name: Checkout SHA
        run: cd package-index && git checkout '${{ github.event.client_payload.sha }}'

      - name: Lune build website
        run: |
          lune run moonwave-build

      - name: Commit changes
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git add .
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -m "Auto-update documentation '${{ github.event.client_payload.sha }}'" && git push || echo "No changes to commit"
